--
-- Copyright (c) 2023 Oracle
--
-- Permission is hereby granted, free of charge, to any person obtaining a
-- copy of this software and associated documentation files (the "Software"),
-- to deal in the Software without restriction, including without limitation
-- the rights to use, copy, modify, merge, publish, distribute, sublicense,
-- and/or sell copies of the Software, and to permit persons to whom the
-- Software is furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
-- THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-- FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
-- DEALINGS IN THE SOFTWARE.
--
-- NAME
--   co_create.sql - Creates schema objects for CO (Customer Orders) schema
--
-- DESCRIPTION
--   PostgreSQL 17 port of the Oracle CO schema.
--   This script creates tables, associated constraints,
--   indexes, views, and comments in the CO schema.
--
-- SCHEMA VERSION
--   21
--
-- ORIGINAL RELEASE DATE
--   08-FEB-2022
--
-- SUPPORTED with DB VERSIONS
--   PostgreSQL 17 and higher
--
-- SCHEMA DEPENDENCIES AND REQUIREMENTS
--   This script is called from the co_install.sql script
--
-- INSTALL INSTRUCTIONS
--   Run the co_install.sql script to call this script
--
-- --------------------------------------------------------------------------

-- ********************************************************************
-- Create the CUSTOMERS table to hold customer information

\echo '******  Creating CUSTOMERS table ....'

CREATE TABLE customers
(
  customer_id     INTEGER GENERATED BY DEFAULT AS IDENTITY,
  email_address   VARCHAR(255) NOT NULL,
  full_name       VARCHAR(255) NOT NULL
);


-- ********************************************************************
-- Create the STORES table to hold store information

\echo '******  Creating STORES table ....'

CREATE TABLE stores
(
  store_id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
  store_name          VARCHAR(255) NOT NULL,
  web_address         VARCHAR(100),
  physical_address    VARCHAR(512),
  latitude            NUMERIC(9,6),
  longitude           NUMERIC(9,6),
  logo                BYTEA,
  logo_mime_type      VARCHAR(512),
  logo_filename       VARCHAR(512),
  logo_charset        VARCHAR(512),
  logo_last_updated   TIMESTAMP
);


-- ********************************************************************
-- Create the PRODUCTS table to hold product information

\echo '******  Creating PRODUCTS table ....'

CREATE TABLE products
(
  product_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
  product_name         VARCHAR(255) NOT NULL,
  unit_price           NUMERIC(10,2),
  product_details      JSONB,
  product_image        BYTEA,
  image_mime_type      VARCHAR(512),
  image_filename       VARCHAR(512),
  image_charset        VARCHAR(512),
  image_last_updated   TIMESTAMP
);

-- ********************************************************************
-- Create the ORDERS table to hold orders information

\echo '******  Creating ORDERS table ....'

CREATE TABLE orders
(
  order_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
  order_tms      TIMESTAMP NOT NULL,
  customer_id    INTEGER NOT NULL,
  order_status   VARCHAR(10) NOT NULL,
  store_id       INTEGER NOT NULL
);

-- ********************************************************************
-- Create the SHIPMENTS table to hold shipment information

\echo '******  Creating SHIPMENTS table ....'

CREATE TABLE shipments
(
  shipment_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
  store_id           INTEGER NOT NULL,
  customer_id        INTEGER NOT NULL,
  delivery_address   VARCHAR(512) NOT NULL,
  shipment_status    VARCHAR(100) NOT NULL
);

-- ********************************************************************
-- Create the ORDER_ITEMS table to hold order item information for orders

\echo '******  Creating ORDER_ITEMS table ....'

CREATE TABLE order_items
(
  order_id       INTEGER NOT NULL,
  line_item_id   INTEGER NOT NULL,
  product_id     INTEGER NOT NULL,
  unit_price     NUMERIC(10,2) NOT NULL,
  quantity       INTEGER NOT NULL,
  shipment_id    INTEGER
);

-- ********************************************************************
-- Create the INVENTORY table to hold inventory information

\echo '******  Creating INVENTORY table ....'

CREATE TABLE inventory
(
  inventory_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
  store_id            INTEGER NOT NULL,
  product_id          INTEGER NOT NULL,
  product_inventory   INTEGER NOT NULL
);

-- ********************************************************************
-- Create views

\echo '******  Creating views ....'

-- ********************************************************************
-- A view for a summary of who placed each order and what they bought
--
-- Conversion notes:
--   LISTAGG(...ON OVERFLOW TRUNCATE '...' WITH COUNT) WITHIN GROUP (ORDER BY ...)
--   is replaced by STRING_AGG(... ORDER BY ...).
--   PostgreSQL STRING_AGG has no built-in overflow truncation; the full
--   concatenated string is returned.

CREATE OR REPLACE VIEW customer_order_products AS
  SELECT o.order_id, o.order_tms, o.order_status,
         c.customer_id, c.email_address, c.full_name,
         SUM ( oi.quantity * oi.unit_price ) AS order_total,
         STRING_AGG (
           p.product_name, ', '
           ORDER BY oi.line_item_id
         ) AS items
  FROM   orders o
  JOIN   order_items oi
  ON     o.order_id = oi.order_id
  JOIN   customers c
  ON     o.customer_id = c.customer_id
  JOIN   products p
  ON     oi.product_id = p.product_id
  GROUP  BY o.order_id, o.order_tms, o.order_status,
         c.customer_id, c.email_address, c.full_name;

-- ********************************************************************
-- A view for a summary of what was purchased at each location,
--    including summaries each store, order status and overall total
--
-- Conversion notes:
--   GROUPING_ID(a,b) is rewritten as GROUPING(a) * 2 + GROUPING(b)
--   to produce the same bitmask values (1, 2, 3).
--   NVL is replaced with COALESCE (semantically identical here).

CREATE OR REPLACE VIEW store_orders AS
  SELECT CASE
           GROUPING(s.store_name) * 2 + GROUPING(o.order_status)
           WHEN 1 THEN 'STORE TOTAL'
           WHEN 2 THEN 'STATUS TOTAL'
           WHEN 3 THEN 'GRAND TOTAL'
         END AS total,
         s.store_name,
         COALESCE ( s.web_address, s.physical_address ) AS address,
         s.latitude, s.longitude,
         o.order_status,
         COUNT ( DISTINCT o.order_id ) AS order_count,
         SUM ( oi.quantity * oi.unit_price ) AS total_sales
  FROM   stores s
  JOIN   orders o
  ON     s.store_id = o.store_id
  JOIN   order_items oi
  ON     o.order_id = oi.order_id
  GROUP  BY GROUPING SETS (
    ( s.store_name, COALESCE ( s.web_address, s.physical_address ), s.latitude, s.longitude ),
    ( s.store_name, COALESCE ( s.web_address, s.physical_address ), s.latitude, s.longitude, o.order_status ),
    o.order_status,
    ()
  );

-- ********************************************************************
-- A relational view of the reviews stored in the JSON for each product
--
-- Conversion notes:
--   Oracle JSON_TABLE(...) is replaced by a LATERAL join against
--   jsonb_array_elements(product_details->'reviews').
--   product_details is now JSONB, so no RAW/BLOB casting is needed.

CREATE OR REPLACE VIEW product_reviews AS
  SELECT p.product_name,
         (r.elem->>'rating')::INTEGER AS rating,
         ROUND (
           AVG ( (r.elem->>'rating')::INTEGER ) OVER (
             PARTITION BY p.product_name
           ),
           2
         ) AS avg_rating,
         r.elem->>'review' AS review
  FROM   products p,
         LATERAL jsonb_array_elements( p.product_details->'reviews' ) AS r(elem)
  WHERE  p.product_details IS NOT NULL;

-- ********************************************************************
-- A view for a summary of the total sales per product and order status

CREATE OR REPLACE VIEW product_orders AS
  SELECT p.product_name, o.order_status,
         SUM ( oi.quantity * oi.unit_price ) AS total_sales,
         COUNT (*) AS order_count
  FROM   orders o
  JOIN   order_items oi
  ON     o.order_id = oi.order_id
  JOIN   customers c
  ON     o.customer_id = c.customer_id
  JOIN   products p
  ON     oi.product_id = p.product_id
  GROUP  BY p.product_name, o.order_status;


-- ********************************************************************
-- Create indexes

\echo '******  Creating indexes ...'

CREATE INDEX customers_name_i          ON customers   ( full_name );
CREATE INDEX orders_customer_id_i      ON orders      ( customer_id );
CREATE INDEX orders_store_id_i         ON orders      ( store_id );
CREATE INDEX shipments_store_id_i      ON shipments   ( store_id );
CREATE INDEX shipments_customer_id_i   ON shipments   ( customer_id );
CREATE INDEX order_items_shipment_id_i ON order_items ( shipment_id );
CREATE INDEX inventory_product_id_i    ON inventory   ( product_id );

-- ********************************************************************
-- Create constraints

\echo '******  Adding constraints to tables ...'

ALTER TABLE customers ADD CONSTRAINT customers_pk PRIMARY KEY (customer_id);

ALTER TABLE customers ADD CONSTRAINT customers_email_u UNIQUE (email_address);

ALTER TABLE stores ADD CONSTRAINT stores_pk PRIMARY KEY (store_id);

ALTER TABLE stores ADD CONSTRAINT store_name_u UNIQUE (store_name);

ALTER TABLE stores ADD CONSTRAINT store_at_least_one_address_c
  CHECK (
    web_address IS NOT NULL OR physical_address IS NOT NULL
  );

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY (product_id);

-- Note: Oracle CHECK (product_details IS JSON) is removed because the
-- product_details column uses the JSONB type, which inherently validates
-- that stored values are valid JSON.

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY (order_id);

ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fk
   FOREIGN KEY (customer_id) REFERENCES customers (customer_id);

ALTER TABLE orders ADD CONSTRAINT orders_status_c
                  CHECK ( order_status IN
                    ( 'CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED'));

ALTER TABLE orders ADD CONSTRAINT orders_store_id_fk FOREIGN KEY (store_id)
   REFERENCES stores (store_id);

ALTER TABLE shipments ADD CONSTRAINT shipments_pk PRIMARY KEY (shipment_id);

ALTER TABLE shipments ADD CONSTRAINT shipments_store_id_fk
   FOREIGN KEY (store_id) REFERENCES stores (store_id);

ALTER TABLE shipments ADD CONSTRAINT shipments_customer_id_fk
   FOREIGN KEY (customer_id) REFERENCES customers (customer_id);

ALTER TABLE shipments ADD CONSTRAINT shipment_status_c
                  CHECK ( shipment_status IN
                    ( 'CREATED', 'SHIPPED', 'IN-TRANSIT', 'DELIVERED'));

ALTER TABLE order_items ADD CONSTRAINT order_items_pk PRIMARY KEY ( order_id, line_item_id );

ALTER TABLE order_items ADD CONSTRAINT order_items_order_id_fk
   FOREIGN KEY (order_id) REFERENCES orders (order_id);

ALTER TABLE order_items ADD CONSTRAINT order_items_shipment_id_fk
   FOREIGN KEY (shipment_id) REFERENCES shipments (shipment_id);

ALTER TABLE order_items ADD CONSTRAINT order_items_product_id_fk
   FOREIGN KEY (product_id) REFERENCES products (product_id);

ALTER TABLE order_items ADD CONSTRAINT order_items_product_u UNIQUE ( product_id, order_id );

ALTER TABLE inventory ADD CONSTRAINT inventory_pk PRIMARY KEY (inventory_id);

ALTER TABLE inventory ADD CONSTRAINT inventory_store_product_u UNIQUE (store_id, product_id);

ALTER TABLE inventory ADD CONSTRAINT inventory_store_id_fk
   FOREIGN KEY (store_id) REFERENCES stores (store_id);

ALTER TABLE inventory ADD CONSTRAINT inventory_product_id_fk
   FOREIGN KEY (product_id) REFERENCES products (product_id);

-- ********************************************************************
-- Add table and column comments

\echo '******  Adding table column comments ...'

COMMENT ON TABLE customers
  IS 'Details of the people placing orders';

COMMENT ON COLUMN customers.customer_id
  IS 'Auto-incrementing primary key';

COMMENT ON COLUMN customers.email_address
  IS 'The email address the person uses to access the account';

COMMENT ON COLUMN customers.full_name
  IS 'What this customer is called';

COMMENT ON TABLE stores
  IS 'Physical and virtual locations where people can purchase products';

COMMENT ON COLUMN stores.store_id
  IS 'Auto-incrementing primary key';

COMMENT ON COLUMN stores.store_name
  IS 'What the store is called';

COMMENT ON COLUMN stores.web_address
  IS 'The URL of a virtual store';

COMMENT ON COLUMN stores.physical_address
  IS 'The postal address of this location';

COMMENT ON COLUMN stores.latitude
  IS 'The north-south position of a physical store';

COMMENT ON COLUMN stores.longitude
  IS 'The east-west position of a physical store';

COMMENT ON COLUMN stores.logo
  IS 'An image used by this store';

COMMENT ON COLUMN stores.logo_mime_type
  IS 'The mime-type of the store logo';

COMMENT ON COLUMN stores.logo_last_updated
  IS 'The date the image was last changed';

COMMENT ON COLUMN stores.logo_filename
  IS 'The name of the file loaded in the image column';

COMMENT ON COLUMN stores.logo_charset
  IS 'The character set used to encode the image';

COMMENT ON TABLE products
  IS 'Details of goods that customers can purchase';

COMMENT ON COLUMN products.product_id
  IS 'Auto-incrementing primary key';

COMMENT ON COLUMN products.unit_price
  IS 'The monetary value of one item of this product';

COMMENT ON COLUMN products.product_details
  IS 'Further details of the product stored in JSONB format';

COMMENT ON COLUMN products.product_image
  IS 'A picture of the product';

COMMENT ON COLUMN products.image_mime_type
  IS 'The mime-type of the product image';

COMMENT ON COLUMN products.image_last_updated
  IS 'The date the image was last changed';

COMMENT ON COLUMN products.image_filename
  IS 'The name of the file loaded in the image column';

COMMENT ON COLUMN products.image_charset
  IS 'The character set used to encode the image';

COMMENT ON COLUMN products.product_name
  IS 'What a product is called';

COMMENT ON TABLE orders
  IS 'Details of who made purchases where';

COMMENT ON COLUMN orders.order_id
  IS 'Auto-incrementing primary key';

COMMENT ON COLUMN orders.order_tms
  IS 'When the order was placed';

COMMENT ON COLUMN orders.customer_id
  IS 'Who placed this order';

COMMENT ON COLUMN orders.store_id
  IS 'Where this order was placed';

COMMENT ON COLUMN orders.order_status
  IS 'What state the order is in. Valid values are:
OPEN - the order is in progress
PAID - money has been received from the customer for this order
SHIPPED - the products have been dispatched to the customer
COMPLETE - the customer has received the order
CANCELLED - the customer has stopped the order
REFUNDED - there has been an issue with the order and the money has been returned to the customer';

COMMENT ON TABLE order_items
  IS 'Details of which products the customer has purchased in an order';

COMMENT ON COLUMN order_items.order_id
  IS 'The order these products belong to';

COMMENT ON COLUMN order_items.line_item_id
  IS 'An incrementing number, starting at one for each order';

COMMENT ON COLUMN order_items.product_id
  IS 'Which item was purchased';

COMMENT ON COLUMN order_items.unit_price
  IS 'How much the customer paid for one item of the product';

COMMENT ON COLUMN order_items.quantity
  IS 'How many items of this product the customer purchased';

COMMENT ON COLUMN order_items.shipment_id
  IS 'Where this product will be delivered';

COMMENT ON TABLE customer_order_products
  IS 'A summary of who placed each order and what they bought';

COMMENT ON COLUMN customer_order_products.order_id
  IS 'The primary key of the order';

COMMENT ON COLUMN customer_order_products.order_tms
  IS 'The date and time the order was placed';

COMMENT ON COLUMN customer_order_products.order_status
  IS 'The current state of this order';

COMMENT ON COLUMN customer_order_products.customer_id
  IS 'The primary key of the customer';

COMMENT ON COLUMN customer_order_products.email_address
  IS 'The email address the person uses to access the account';

COMMENT ON COLUMN customer_order_products.full_name
  IS 'What this customer is called';

COMMENT ON COLUMN customer_order_products.order_total
  IS 'The total amount the customer paid for the order';

COMMENT ON COLUMN customer_order_products.items
  IS 'A comma-separated list naming the products in this order';

COMMENT ON TABLE store_orders
  IS 'A summary of what was purchased at each location, including summaries each store, order status and overall total';

COMMENT ON COLUMN store_orders.order_status
  IS 'The current state of this order';

COMMENT ON COLUMN store_orders.total
  IS 'Indicates what type of total is displayed, including Store, Status, or Grand Totals';

COMMENT ON COLUMN store_orders.store_name
  IS 'What the store is called';

COMMENT ON COLUMN store_orders.latitude
  IS 'The north-south position of a physical store';

COMMENT ON COLUMN store_orders.longitude
  IS 'The east-west position of a physical store';

COMMENT ON COLUMN store_orders.address
  IS 'The physical or virtual location of this store';

COMMENT ON COLUMN store_orders.total_sales
  IS 'The total value of orders placed';

COMMENT ON COLUMN store_orders.order_count
  IS 'The total number of orders placed';

COMMENT ON TABLE product_reviews
  IS 'A relational view of the reviews stored in the JSON for each product';

COMMENT ON COLUMN product_reviews.product_name
  IS 'What this product is called';

COMMENT ON COLUMN product_reviews.rating
  IS 'The review score the customer has placed. Range is 1-10';

COMMENT ON COLUMN product_reviews.avg_rating
  IS 'The mean of the review scores for this product';

COMMENT ON COLUMN product_reviews.review
  IS 'The text of the review';

COMMENT ON TABLE product_orders
  IS 'A summary of the state of the orders placed for each product';

COMMENT ON COLUMN product_orders.product_name
  IS 'What this product is called';

COMMENT ON COLUMN product_orders.order_status
  IS 'The current state of these order';

COMMENT ON COLUMN product_orders.total_sales
  IS 'The total value of orders placed';

COMMENT ON COLUMN product_orders.order_count
  IS 'The total number of orders placed';

COMMENT ON TABLE shipments
  IS 'Details of where ordered goods will be delivered';

COMMENT ON COLUMN shipments.shipment_id
  IS 'Auto-incrementing primary key';

COMMENT ON COLUMN shipments.store_id
  IS 'Which location the goods will be transported from';

COMMENT ON COLUMN shipments.customer_id
  IS 'Who this shipment is for';

COMMENT ON COLUMN shipments.delivery_address
  IS 'Where the goods will be transported to';

COMMENT ON COLUMN shipments.shipment_status
  IS 'The current status of the shipment. Valid values are:
CREATED - the shipment is ready for order assignment
SHIPPED - the goods have been dispatched
IN-TRANSIT - the goods are en-route to their destination
DELIVERED - the good have arrived at their destination';

COMMENT ON TABLE inventory
  IS 'Details of the quantity of stock available for products at each location';

COMMENT ON COLUMN inventory.inventory_id
  IS 'Auto-incrementing primary key';

COMMENT ON COLUMN inventory.store_id
  IS 'Which location the goods are located at';

COMMENT ON COLUMN inventory.product_id
  IS 'Which item this stock is for';

COMMENT ON COLUMN inventory.product_inventory
  IS 'The current quantity in stock';
